version: '3'
services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    ports:
      - "3000:3000"
    command: bash -c 'yarn && yarn run dev --host'
volumes:
  node_modules:
